
title: "ORBIT LAB"
description: "One-chip Realization of Boundless Integrated Technology"
remote_theme: just-the-docs/just-the-docs
baseurl: "/orbit_lab"

color_scheme: light

nav:
  - Home: index.md
  - About: pages/about.md
  - Research: pages/research.md
  - Join Us: pages/join.md
  - Publications: pages/publications.md
