
title: "ORBIT LAB"
description: "One-chip Realization of Boundless Integrated Technology"
remote_theme: just-the-docs/just-the-docs
baseurl: "/orbit_lab"

color_scheme: light

nav:
  - Home: index.md
  - Members: pages/members.md
  - Research: pages/research.md
  - Join Us: pages/join.md
  - Publications: pages/publications.md

footer_content: |
  <div style="display: flex; justify-content: space-between; align-items: center;">
    <div style="text-align: left;">
      <strong>© 2025 ORBIT LAB</strong> (Department of System Semiconductor Engineering, Cheongju University)<br>
      <strong>Contact</strong><br>
      [Tel] +82-43-229-8443<br>
      <a href="mailto:doojinjang@cju.ac.kr">[E-mail] doojinjang at cju.ac.kr</a>
    </div>
    <img src="/orbit_lab/assets/img/cju_ui.png" alt="CJU Logo" style="height: 50px;">
  </div>
