
title: "ORBIT LAB"
description: "One-chip Realization of Boundless Integrated Technology"
remote_theme: just-the-docs/just-the-docs
baseurl: "/orbit_lab"

color_scheme: light

aux_links:
  "Cheongju University":
    - "https://www.cju.ac.kr/"

nav_external_links:
  - title: GitHub
    url: https://github.com/doojin83
    hide_icon: false
