
title: "ORBIT LAB"
description: "One-chip Realization of Boundless Integrated Technology"
theme: just-the-docs

url: "https://doojin83.github.io"
baseurl: "/orbit_lab"

color_scheme: light

aux_links:
  "Cheongju University":
    - "https://www.cju.ac.kr/"

nav_external_links:
  - title: GitHub
    url: https://github.com/doojin83
    hide_icon: false
