
title: "ORBIT LAB"
description: "One-chip Realization of Boundless Integrated Technology"
remote_theme: just-the-docs/just-the-docs
baseurl: "/orbit_lab"

color_scheme: light

nav:
  - Home: index.md
  - Members: 
    - Professor: pages/members/professor.md
    - Students: pages/members/students.md
    - Alumni: pages/members/alumni.md
  - Research: pages/research.md
  - Join Us: pages/join.md
  - Publications: pages/publications.md

just_the_docs:
  footer_content: ""
  footer_custom: footer_custom.html
