title: "ORBIT LAB"
description: "One-chip Realization of Boundless Integrated Technology"
baseurl: "/orbit_lab"  # 리포지토리 이름
url: "https://doojin83.github.io"  # 사용자 도메인

theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag

# ✅ _pages 디렉토리 인식 설정
collections:
  pages:
    output: true
    permalink: /:path/
    directory: _pages

# ✅ default 값 지정
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      permalink: /:basename/

# ✅ 내비게이션 메뉴 (선택)
navigation:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "Join"
    url: /join/
  - title: "Publications"
    url: /publications/
